"""add borrower_id

Revision ID: 0345b728152f
Revises: 7e70389375e3
Create Date: 2026-08-05 13:10:02.226946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0345b728152f'
down_revision: Union[str, Sequence[str], None] = '7e70389375e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('borrower_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['borrower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'borrower_id')
    # ### end Alembic commands ###
