name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run linter e tests
    runs-on: ubuntu-latest
    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4
      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Instalar o UV da Astral
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Instalar as dependências
        run: uv sync --frozen
      - name: Executa o lint 
        run: uv run task lint 
      - name: Executa os testes
        run: uv run task test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}